language: java
jdk:
  - openjdk11

branches:
  only:
    - master
    - "/^v[0-9]+(\\.[0-9]+)+/"

after_success:
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings travis-settings.xml
  - mvn dockerfile:build
  - mvn dockerfile:tag@tag-version
  - mvn dockerfile:push@push-latest -Ddockerfile.useMavenSettingsForAuth=true --settings travis-settings.xml
  - mvn dockerfile:push@push-version -Ddockerfile.useMavenSettingsForAuth=true --settings travis-settings.xml

cache:
  directories:
    - '$HOME/.m2/repository'

services:
  - docker

env:
  global:
    # travis encrypt BINTRAY_USER=[username]
    - secure: ss5yQliTTE9a4WmW4jwTABZe9MLHeT/qTxyiW0PryjiHVkuOwN1NhkxmfiCf95UGqjpKm5Pz5TPnL46rCXE/BDl9YtW+59RqMSKzBZrsyREgtZ/Z6w/s/sYzFHgOoC4T6waujR3vblnjv3mjapKaypXAxmfCAeIo5GPi77KOhQ6cXkl0ZTBFJNsU3bn18mWNN3EVTykRivNI44H99g6jML7DQn53F1YiFGXa9pnBkA2IYQdpPLSzxwymfN2mbT21Lbvq/nAPxXWjmuK7wLBwYG9cOAVXSOB1JK3iqQr2luvFTiIMLXeJqOuJq/HiGL/IbVkE1YoQwSO1kB28hnkuVj+9Baof2LakflnZavrRQth9oUNGdD07tVd4vVRrn1L6zzrAW9pjv/CTNLjYJ0PzFmW5PVh4YMRH+JNWYNe3ue0UTBqFZ8PQptLCoHOOcr0A2RiR+b6hsL+izHIt/q3BVUz55IPr4tWvGMauRMyUDm871QM2t3FfHc87gyMh98kbjbdgJSl7jVDrhc3vGy0+uoiW67F7EoaYzETZWtsi5TL+KiwGCZyiTxq8P5MeiqexUjDop1OoeN04E0VxKJUnClmoh0CnNktYduxGtYUZ6dQZ77hSjOHH74MH+TuO3xqRXyzO34zvX7tK2vtVuH75SnpFdJrwduOrOLRroGNPhHo=
    # travis encrypt BINTRAY_API_KEY=[api key]
    - secure: hItEp2hUUg2IDEHwTk6QldlK5uVEucw4SutfGKqYz8B/qsGLGpbMgNYXc2w0A6I0Ci9Ey6ZRMuNv2ZLNaR6J+q/kAFIGqmos5cxAbKwfv2KBkJFt/N6zyEMIbAv9e4LFXJzjOTnokx3AhN6mWM1njfUMTV17kS+i6Lf84T6GVjfuLnJKRRQqrghxTkuZJSxBkpZPKSltNif3r79YqakA3r+piyNL1+LpT6F534I9g4FlFx5BZbxmX6W1KajmSTK7uYljeoMR8Zul5Q0bmoPc/wG2E7FBPBmNRvPT5tBeVTECsDExRY1w5u244eilo99dfykmFDr7zcAJtb6qogTyL0jR89cBQ36gxsRRXkXtzLb0MXr/rtp9d4Z6mz6nfFXi6OYzHo711UP7Jg8I8UcRKbRKF8lSSTwKHhqIBHp2itLJL1tdZew+qBnB+D1q3SMLnXN+GhzLnJX32sLKVLUMWIfSTCMjsgmpRvgOSfdunSD17+YwtEssOdlJxoXCugpECyFG4cEbYgevsK5n0ySzSa5qyKWB72N0zlMAXJ3vLxfjUo/C7AQdDrYVbKDbv/UKsPqfxbh4iPeU437G5H9PZh3ufI9c8XaiVPXTMX64dT/NcL6FaO31/6Lpl1dAL9yZK80/hbdAGbqIEnn2XtVmR/dNCXV7vGrWEF5izBzCZCw=
    # travis encrypt DOCKER_USERNAME=[username]
    - secure: dbKWVcgMpnyJGQ1hSTfw+bcqwNlqHjbxevZNvlWmnuOJ29Ohwc1ZM3foWEbX8XWnhS0Qf3jQdjQnpQskHgDNV7xBTTz19rq51VZ58Z62tk5O97W4oyQqB7vNirAipI/jcmT0kvUjk/4KMoMrfLdMBVeMBt3P0nCNj6cY9nDJg8uKgfDY0T2286hPn/2jNjGHhBmD0RDLzuTrB++NLYtPqmTazBWS2tTJUFZqznQ/7dSwP/fqPr/kOydjBlSM14npx2M8U0kXCXNdLO66U4ERW1fk19V4Ys6vK9hU64aRrdnlAhYGFqS8uQ73SI/y8RYJz040+ncAeWPW+5jX3UF5ml7DgD3P5pFTa8QtLzJ5H0fDzvv3/wUHnfnZ1bFCDQMI6czcM8gqMNMQWiziSqlrSDUZgfq32JtYG0qvXisJCJIHWmRycEiv2UfOyfT1uTgvscGfTxTEBlgSn0oqwCKbt1ANVmDSYVXRDOitMvr0genVxXh+QundD6nBHVYiS0CWzMQTVN+us6yvPDMW1+koVNGlbZsfW4ujMWta8/BeDsHsmQF7pFdzj4b1XKBokU/pIg+pNPh2f8nzvBBnMqduPBCV8fMgZKqbkPTD0xQYEsaYZgGN9DjE6V4q8ZaMpdB+Dy3xUdT4+fyWoKVGyplTfIwiNu1gBxkHcf848txgSmQ=
    # travis encrypt DOCKER_PASSWORD=[password]
    - secure: aY9Z+aj3rZC1tIrWv6GJkhtjofeHfEsOFGzXav3s7NOUJSaXe+TtlA/dTZhybwGBugecuVcMEl3Cc9PlXN4SGGpYVRXbtYV1ztquMYP0V4LRA+tEXdhcWAB4Ck2E3jjpDj9hhRm6SuAqklUCnICkcsJX8Cme1MRnmeKK3OlsDYoIRCWoqFEpbl82Citj6y7vfrX1ncjZvpQ7BO/u3LAGtJDGcpYWlIKwNp5dfQoimlrdiyDI4rBlMUZ8nAC3u5TYp1M0zQJGG0A9LyDPTP6yOKsjJkT2XKUrBrFVmchQGJIecl80yPAulCOJBFKI7zR3h2jnCjQxDHX19nV7rHZLUYZ1zC5mTtUuK+2+aKuJODYV+YcbqBve7eQC4oYS6iw6SLgRZp+gvI0SQpihl/VU1wRdmesCo5yTkZlZW0Ob3cm9T/Y2rS4ib2WDlzXjSEwumsXOfKLYRLsIPQcxbYFUhMaWUlWtgYk92rNNx0wGYm90qKOWhdZopoD6e61zIy5yR0SCMavJtwPmR40s7uBTXB0vyt+LgKRl/oWgqZbsTOTwttvTOZltG9MrmurY0Gsn0S/y+dujmREwb7d6tGvaV8aCgpRkDqASy1R1Zdd8K0klLVdbDI3jZS6pfT3vzNgKKOpXigkcBEG0ogOsxt9H2dMmj3Y44vcqXgDi/znPoao=